repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks: # https://github.com/pre-commit/pre-commit-hooks#hooks-available
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer # https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file
        exclude: ^(bruno/collection.json)$ # Excluded to avoid issues with Bruno importing the collection.json
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.0'  # Must be updated manually (see https://python-poetry.org/docs/pre-commit-hooks/#why-does-pre-commit-autoupdate-not-update-to-the-latest-version
    hooks:
# TODO: Uncomment when dependabot uses poetry 2.x.x. See https://github.com/dependabot/dependabot-core/issues/11237
#      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        pass_filenames: false  # Pass all files in the repository except those excluded in pyproject.toml
        args:
          - '.'  # Check all files in the repository
          - "--config-file=pyproject.toml"
        additional_dependencies:
          - 'pydantic'
          - 'fastapi'
          - 'pytest'

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.2"
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, -r, -l]
        additional_dependencies: ["bandit[toml]"]
