name: Update Dependencies
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: "pip"

      - name: Install Pre-Commit and yq
        run: |
          pip install pre-commit yq

      - name: Extract Repos Excluding Poetry
        id: extract_repos
        run: |
          # Extract repos, excluding the one for Poetry
          EXCLUDED_REPO="https://github.com/python-poetry/poetry"

          REPOS=$(yq '.repos[].repo' .pre-commit-config.yaml | \
            grep -v "$EXCLUDED_REPO" | \
            xargs -n1 echo --repo)

          # Save consolidated repo flags to an output variable
          echo "repos=${REPOS}" >> "$GITHUB_OUTPUT"

      - name: Run Pre-Commit Autoupdate
        run: |
          pre-commit autoupdate ${{ steps.extract_repos.outputs.repos }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore: update pre-commit hooks'
          commit-message: 'chore: update pre-commit hooks'
          branch: update-pre-commit-hooks
